version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped

  frontend:
    build: ./frontend/issue-tracker-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped